import = [
    "~/.config/alacritty/themes/gruvbox_material_hard_dark_nom.toml"
]

[ env ]
TERM = "xterm-256color"


[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
dimensions = {columns = 150, lines = 52}

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 15

