# Customized by noeddi2be
# Colors (Gruvbox Material Hard Dark)

# Default colors
[colors.primary]
background = '#172027'
foreground = '#C7D0D8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#CAD1D6"
cursor = "#7daea3"

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
